// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/student.proto

// Define the package name

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the request message for GetStudent
type StudentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A field to specify the student ID
	StudentId     string `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentRequest) Reset() {
	*x = StudentRequest{}
	mi := &file_proto_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentRequest) ProtoMessage() {}

func (x *StudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentRequest.ProtoReflect.Descriptor instead.
func (*StudentRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{0}
}

func (x *StudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

// Define the response message for GetStudent
type Student struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Define fields for student details
	StudentId              string   `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`                                         // Unique student ID
	Name                   string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                    // Student's name
	Dob                    string   `protobuf:"bytes,3,opt,name=dob,proto3" json:"dob,omitempty"`                                                                      // Date of Birth
	Gender                 string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`                                                                // Gender
	Nationality            string   `protobuf:"bytes,5,opt,name=nationality,proto3" json:"nationality,omitempty"`                                                      // Nationality
	AadharNumber           string   `protobuf:"bytes,6,opt,name=aadhar_number,json=aadharNumber,proto3" json:"aadhar_number,omitempty"`                                // Aadhar or Social Security Number
	ContactNumber          string   `protobuf:"bytes,7,opt,name=contact_number,json=contactNumber,proto3" json:"contact_number,omitempty"`                             // Contact number
	Email                  string   `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`                                                                  // Email address
	PermanentAddress       string   `protobuf:"bytes,9,opt,name=permanent_address,json=permanentAddress,proto3" json:"permanent_address,omitempty"`                    // Permanent address
	CurrentAddress         string   `protobuf:"bytes,10,opt,name=current_address,json=currentAddress,proto3" json:"current_address,omitempty"`                         // Current address
	ParentGuardianName     string   `protobuf:"bytes,11,opt,name=parent_guardian_name,json=parentGuardianName,proto3" json:"parent_guardian_name,omitempty"`           // Parent/Guardian's name
	ParentGuardianContact  string   `protobuf:"bytes,12,opt,name=parent_guardian_contact,json=parentGuardianContact,proto3" json:"parent_guardian_contact,omitempty"`  // Parent/Guardian's contact number
	PreviousInstitution    string   `protobuf:"bytes,13,opt,name=previous_institution,json=previousInstitution,proto3" json:"previous_institution,omitempty"`          // Previous institution name
	PreviousGrade          string   `protobuf:"bytes,14,opt,name=previous_grade,json=previousGrade,proto3" json:"previous_grade,omitempty"`                            // Previous grade/qualification
	MarksObtained          string   `protobuf:"bytes,15,opt,name=marks_obtained,json=marksObtained,proto3" json:"marks_obtained,omitempty"`                            // Marks/grades obtained
	PassingYear            string   `protobuf:"bytes,16,opt,name=passing_year,json=passingYear,proto3" json:"passing_year,omitempty"`                                  // Passing year
	BoardName              string   `protobuf:"bytes,17,opt,name=board_name,json=boardName,proto3" json:"board_name,omitempty"`                                        // Board name (e.g., CBSE, ICSE)
	TransferCertificate    string   `protobuf:"bytes,18,opt,name=transfer_certificate,json=transferCertificate,proto3" json:"transfer_certificate,omitempty"`          // Transfer certificate
	CourseAppliedFor       string   `protobuf:"bytes,19,opt,name=course_applied_for,json=courseAppliedFor,proto3" json:"course_applied_for,omitempty"`                 // Course applied for
	Session                string   `protobuf:"bytes,20,opt,name=session,proto3" json:"session,omitempty"`                                                             // Academic session
	ClassSemester          string   `protobuf:"bytes,21,opt,name=class_semester,json=classSemester,proto3" json:"class_semester,omitempty"`                            // Class/semester
	RegistrationNumber     string   `protobuf:"bytes,22,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`             // Registration number
	AdmissionCategory      string   `protobuf:"bytes,23,opt,name=admission_category,json=admissionCategory,proto3" json:"admission_category,omitempty"`                // Admission category (e.g., General, Reserved)
	Documents              []string `protobuf:"bytes,24,rep,name=documents,proto3" json:"documents,omitempty"`                                                         // List of required documents
	PaymentMode            string   `protobuf:"bytes,25,opt,name=payment_mode,json=paymentMode,proto3" json:"payment_mode,omitempty"`                                  // Payment mode (e.g., Online, Offline)
	ScholarshipEligibility string   `protobuf:"bytes,26,opt,name=scholarship_eligibility,json=scholarshipEligibility,proto3" json:"scholarship_eligibility,omitempty"` // Scholarship eligibility
	LoanAssistance         string   `protobuf:"bytes,27,opt,name=loan_assistance,json=loanAssistance,proto3" json:"loan_assistance,omitempty"`                         // Loan assistance
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_proto_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{1}
}

func (x *Student) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *Student) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Student) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *Student) GetAadharNumber() string {
	if x != nil {
		return x.AadharNumber
	}
	return ""
}

func (x *Student) GetContactNumber() string {
	if x != nil {
		return x.ContactNumber
	}
	return ""
}

func (x *Student) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Student) GetPermanentAddress() string {
	if x != nil {
		return x.PermanentAddress
	}
	return ""
}

func (x *Student) GetCurrentAddress() string {
	if x != nil {
		return x.CurrentAddress
	}
	return ""
}

func (x *Student) GetParentGuardianName() string {
	if x != nil {
		return x.ParentGuardianName
	}
	return ""
}

func (x *Student) GetParentGuardianContact() string {
	if x != nil {
		return x.ParentGuardianContact
	}
	return ""
}

func (x *Student) GetPreviousInstitution() string {
	if x != nil {
		return x.PreviousInstitution
	}
	return ""
}

func (x *Student) GetPreviousGrade() string {
	if x != nil {
		return x.PreviousGrade
	}
	return ""
}

func (x *Student) GetMarksObtained() string {
	if x != nil {
		return x.MarksObtained
	}
	return ""
}

func (x *Student) GetPassingYear() string {
	if x != nil {
		return x.PassingYear
	}
	return ""
}

func (x *Student) GetBoardName() string {
	if x != nil {
		return x.BoardName
	}
	return ""
}

func (x *Student) GetTransferCertificate() string {
	if x != nil {
		return x.TransferCertificate
	}
	return ""
}

func (x *Student) GetCourseAppliedFor() string {
	if x != nil {
		return x.CourseAppliedFor
	}
	return ""
}

func (x *Student) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Student) GetClassSemester() string {
	if x != nil {
		return x.ClassSemester
	}
	return ""
}

func (x *Student) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *Student) GetAdmissionCategory() string {
	if x != nil {
		return x.AdmissionCategory
	}
	return ""
}

func (x *Student) GetDocuments() []string {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *Student) GetPaymentMode() string {
	if x != nil {
		return x.PaymentMode
	}
	return ""
}

func (x *Student) GetScholarshipEligibility() string {
	if x != nil {
		return x.ScholarshipEligibility
	}
	return ""
}

func (x *Student) GetLoanAssistance() string {
	if x != nil {
		return x.LoanAssistance
	}
	return ""
}

var File_proto_student_proto protoreflect.FileDescriptor

const file_proto_student_proto_rawDesc = "" +
	"\n" +
	"\x13proto/student.proto\x12\astudent\"/\n" +
	"\x0eStudentRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"\x92\b\n" +
	"\aStudent\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03dob\x18\x03 \x01(\tR\x03dob\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12 \n" +
	"\vnationality\x18\x05 \x01(\tR\vnationality\x12#\n" +
	"\raadhar_number\x18\x06 \x01(\tR\faadharNumber\x12%\n" +
	"\x0econtact_number\x18\a \x01(\tR\rcontactNumber\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12+\n" +
	"\x11permanent_address\x18\t \x01(\tR\x10permanentAddress\x12'\n" +
	"\x0fcurrent_address\x18\n" +
	" \x01(\tR\x0ecurrentAddress\x120\n" +
	"\x14parent_guardian_name\x18\v \x01(\tR\x12parentGuardianName\x126\n" +
	"\x17parent_guardian_contact\x18\f \x01(\tR\x15parentGuardianContact\x121\n" +
	"\x14previous_institution\x18\r \x01(\tR\x13previousInstitution\x12%\n" +
	"\x0eprevious_grade\x18\x0e \x01(\tR\rpreviousGrade\x12%\n" +
	"\x0emarks_obtained\x18\x0f \x01(\tR\rmarksObtained\x12!\n" +
	"\fpassing_year\x18\x10 \x01(\tR\vpassingYear\x12\x1d\n" +
	"\n" +
	"board_name\x18\x11 \x01(\tR\tboardName\x121\n" +
	"\x14transfer_certificate\x18\x12 \x01(\tR\x13transferCertificate\x12,\n" +
	"\x12course_applied_for\x18\x13 \x01(\tR\x10courseAppliedFor\x12\x18\n" +
	"\asession\x18\x14 \x01(\tR\asession\x12%\n" +
	"\x0eclass_semester\x18\x15 \x01(\tR\rclassSemester\x12/\n" +
	"\x13registration_number\x18\x16 \x01(\tR\x12registrationNumber\x12-\n" +
	"\x12admission_category\x18\x17 \x01(\tR\x11admissionCategory\x12\x1c\n" +
	"\tdocuments\x18\x18 \x03(\tR\tdocuments\x12!\n" +
	"\fpayment_mode\x18\x19 \x01(\tR\vpaymentMode\x127\n" +
	"\x17scholarship_eligibility\x18\x1a \x01(\tR\x16scholarshipEligibility\x12'\n" +
	"\x0floan_assistance\x18\x1b \x01(\tR\x0eloanAssistance2I\n" +
	"\x0eStudentService\x127\n" +
	"\n" +
	"GetStudent\x12\x17.student.StudentRequest\x1a\x10.student.StudentB\tZ\a./protob\x06proto3"

var (
	file_proto_student_proto_rawDescOnce sync.Once
	file_proto_student_proto_rawDescData []byte
)

func file_proto_student_proto_rawDescGZIP() []byte {
	file_proto_student_proto_rawDescOnce.Do(func() {
		file_proto_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_student_proto_rawDesc), len(file_proto_student_proto_rawDesc)))
	})
	return file_proto_student_proto_rawDescData
}

var file_proto_student_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_student_proto_goTypes = []any{
	(*StudentRequest)(nil), // 0: student.StudentRequest
	(*Student)(nil),        // 1: student.Student
}
var file_proto_student_proto_depIdxs = []int32{
	0, // 0: student.StudentService.GetStudent:input_type -> student.StudentRequest
	1, // 1: student.StudentService.GetStudent:output_type -> student.Student
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_student_proto_init() }
func file_proto_student_proto_init() {
	if File_proto_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_student_proto_rawDesc), len(file_proto_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_student_proto_goTypes,
		DependencyIndexes: file_proto_student_proto_depIdxs,
		MessageInfos:      file_proto_student_proto_msgTypes,
	}.Build()
	File_proto_student_proto = out.File
	file_proto_student_proto_goTypes = nil
	file_proto_student_proto_depIdxs = nil
}
